### ISSUE TITLE
Rename boards

### ISSUE THREAD

**Issue by roarfred** [roarfred/AmsToMqttBridge#13]
I think it would be great to rename the boards to a more intuitive convention:
* Board001 -> SimpleMBus_ESP8266
* Board002 -> TSS721_ArduinoShield
* Board003 -> MBus_Simulator

@hlovdal, do you approve? I am open to other names, just more readable

**Comment by hlovdal** [comment]
Yes, by all means.

**Comment by roarfred** [comment]
Ended up using a slightly different naming:
- Board001 -> HAN_ESP_Simple
- Board002 -> HAN_TTL_TSS721
- Board003 -> MBus_Simulator

I think these make more sense
