### ISSUE TITLE
Board 2 - PoE

### ISSUE THREAD

**Issue by Bullhill** [roarfred/AmsToMqttBridge#19]
Mulig å designe Board 2 med mulighet for PoE på den?

Hullene kan være optional å montere så den vil ikke øke kostnaden for de som ikke ønsker å bruke POE

https://www.silvertel.com/images/datasheets/Ag9700-Datasheet-low-cost-isolated-Power-over-Ethernet-PoE-module-solution.pdf

**Comment by roarfred** [comment]
Closing this. Board 2 does not use Ethernet.
For an alternative board with wired Ethernet, doing a PoE might be nice!
