### ISSUE TITLE
Question - NodeMCU Boards

### ISSUE THREAD

**Issue by BergAutomations** [roarfred/AmsToMqttBridge#47]
Hi. This looks like a great project and I am looking forward to start testing this together with my Home Assistant setup ([Hass.io](https://www.home-assistant.io/)).
First of, Im no electronics guy and like to use NodeMCU boards in my projects. 
By looking on the schematics I hope that by using the NodeMCU board I have lying around I can simplify the project a bit. Could any of you confirm that I just need to build the HAN to TTL part with the attached RJ45 contact and connect this directly to the NodeMCU RX/TX? [Schematics](https://github.com/roarfred/AmsToMqttBridge/blob/master/Electrical/HAN_ESP_TSS721/images/schematics.png). Or even simplify even more?

**Comment by xibriz** [comment]
I can't remember the spesifics, but I could not get the NodeMCU board working. It was someting along the lines that the hardware serial is mapped to the UART chip on the board.
