### ISSUE TITLE
Alternative electrical circuit made with KiCad and using TSS721

### ISSUE THREAD

**Issue by hlovdal** [roarfred/AmsToMqttBridge#7]
Hi. I have started on designing an alternative circuit. The main planned differences are:

* The schematic and drawings are made with [KiCad](http://www.kicad-pcb.org/) (free GPL tool), which brings the benefit that everyone can change and update the schematics and PCB<sup>1</sup>.
* Focus on robustness and reliability. I do not trust the simple voltage divider bus signal converter and want to use the industry standard [TSS721](http://www.ti.com/lit/ds/symlink/tss721a.pdf) chip, fully optocoupled to avoid any ground loops.
* Available as an Arduino shield to be a flexible building block in whatever monitoring system you want to make.
* Support for sending data over wire (serial/usb/ethernet).
* Support daisy-chaining.

The question is how to cooperate on this. I can create a separate repository that you just link to or use as a submodule. Or I can fork this and make a pull request into a Electrical2 directory or better, reorganise the Electrical into containing two subdirectories.

What do you prefer?

---------

<sup>1</sup> Currently you have a PCB that cannot (easily) be modified and you have to post notes like "R8 should not be used" instead of just updating it. That is not very good.

**Comment by xibriz** [comment]
I dont have it here on my phone, but one resistor needs a higher value and one need to be added for this to work on Kamstrup.

**Comment by xibriz** [comment]
![ams_schematics](https://user-images.githubusercontent.com/6031195/35196974-89980b0c-fed9-11e7-80ac-235b8a9ab675.PNG)

**Comment by roarfred** [comment]
@hlovdal, great initiative! I totally agree on your comment on the rather useless PCB design. If you make a pull request, I'd love to include something better in this project!

**Comment by hlovdal** [comment]
[Fork](https://github.com/hlovdal/AmsToMqttBridge) made, and pull requests created. Closing issue.
